Allow setting the scale down behaviour
giantswarm/coredns-app pull request #174
Opened 2022-11-25 08:31 UTC by silenteh

The stabilization window is used to restrict the [flapping](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#flapping) of replica count when the metrics used for scaling keep fluctuating

2022-11-25 13:32 UTC, Gacko requested changes

2022-11-25 13:32 UTC, Gacko commented on helm/coredns-app/values.yaml
> +  # while kube-proxy is taking long time to add th scaled up pods to the service
```suggestion
  # while kube-proxy is taking long time to add the scaled up pods to the service
```

2022-11-25 13:32 UTC, Gacko commented on helm/coredns-app/values.yaml
> +      stabilizationWindowSeconds: 600
Could we use the default value of 300 seconds or make it optional?

2022-11-30 08:48 UTC, whites11 approved these changes
makes sense to me

2022-11-30 08:52 UTC, silenteh commented on helm/coredns-app/values.yaml
> +  # while kube-proxy is taking long time to add th scaled up pods to the service
The typo has been fixed

2022-11-30 08:53 UTC, merged