Allow customization of nodeselector for CoreDNS Master Instance
giantswarm/coredns-app pull request #180
Opened 2022-12-21 16:43 UTC by primeroz

This is needed in CAPZ

2022-12-22 09:20 UTC, bavarianbidi approved these changes

2022-12-22 09:21 UTC, bavarianbidi requested changes
`values.schema.json` must be updated

2022-12-22 11:04 UTC, fiunchinho approved these changes

2022-12-22 11:42 UTC, primeroz commented
> values.schema.json must be updated.

Actually i think this app does not have a schema.json at all at the moment ? I will add it

2022-12-23 15:00 UTC, Gacko approved these changes

2022-12-28 08:56 UTC, bavarianbidi approved these changes

2022-12-28 09:25 UTC, merged